// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: pkg/pb/tweet/tweet.proto

package tweet

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Descritption string `protobuf:"bytes,2,opt,name=descritption,proto3" json:"descritption,omitempty"`
	File         []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *AddTweetRequest) Reset() {
	*x = AddTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTweetRequest) ProtoMessage() {}

func (x *AddTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTweetRequest.ProtoReflect.Descriptor instead.
func (*AddTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *AddTweetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddTweetRequest) GetDescritption() string {
	if x != nil {
		return x.Descritption
	}
	return ""
}

func (x *AddTweetRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type AddTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTweetResponse) Reset() {
	*x = AddTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTweetResponse) ProtoMessage() {}

func (x *AddTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTweetResponse.ProtoReflect.Descriptor instead.
func (*AddTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{1}
}

type AddTweet2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Descritption string `protobuf:"bytes,2,opt,name=descritption,proto3" json:"descritption,omitempty"`
}

func (x *AddTweet2Request) Reset() {
	*x = AddTweet2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTweet2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTweet2Request) ProtoMessage() {}

func (x *AddTweet2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTweet2Request.ProtoReflect.Descriptor instead.
func (*AddTweet2Request) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{2}
}

func (x *AddTweet2Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddTweet2Request) GetDescritption() string {
	if x != nil {
		return x.Descritption
	}
	return ""
}

type AddTweet2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTweet2Response) Reset() {
	*x = AddTweet2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTweet2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTweet2Response) ProtoMessage() {}

func (x *AddTweet2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTweet2Response.ProtoReflect.Descriptor instead.
func (*AddTweet2Response) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{3}
}

type GetOurTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOurTweetRequest) Reset() {
	*x = GetOurTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOurTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOurTweetRequest) ProtoMessage() {}

func (x *GetOurTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOurTweetRequest.ProtoReflect.Descriptor instead.
func (*GetOurTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{4}
}

func (x *GetOurTweetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TweetReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url         string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Time        *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TweetReponse) Reset() {
	*x = TweetReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetReponse) ProtoMessage() {}

func (x *TweetReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetReponse.ProtoReflect.Descriptor instead.
func (*TweetReponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{5}
}

func (x *TweetReponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TweetReponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TweetReponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TweetReponse) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GetOurTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postdetails []*TweetReponse `protobuf:"bytes,1,rep,name=postdetails,proto3" json:"postdetails,omitempty"`
}

func (x *GetOurTweetResponse) Reset() {
	*x = GetOurTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOurTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOurTweetResponse) ProtoMessage() {}

func (x *GetOurTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOurTweetResponse.ProtoReflect.Descriptor instead.
func (*GetOurTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{6}
}

func (x *GetOurTweetResponse) GetPostdetails() []*TweetReponse {
	if x != nil {
		return x.Postdetails
	}
	return nil
}

type GetOthersTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOthersTweetRequest) Reset() {
	*x = GetOthersTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOthersTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOthersTweetRequest) ProtoMessage() {}

func (x *GetOthersTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOthersTweetRequest.ProtoReflect.Descriptor instead.
func (*GetOthersTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{7}
}

func (x *GetOthersTweetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOthersTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postdetailss []*TweetReponse `protobuf:"bytes,1,rep,name=postdetailss,proto3" json:"postdetailss,omitempty"`
}

func (x *GetOthersTweetResponse) Reset() {
	*x = GetOthersTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOthersTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOthersTweetResponse) ProtoMessage() {}

func (x *GetOthersTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOthersTweetResponse.ProtoReflect.Descriptor instead.
func (*GetOthersTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{8}
}

func (x *GetOthersTweetResponse) GetPostdetailss() []*TweetReponse {
	if x != nil {
		return x.Postdetailss
	}
	return nil
}

type EditTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid      int64  `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *EditTweetRequest) Reset() {
	*x = EditTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTweetRequest) ProtoMessage() {}

func (x *EditTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTweetRequest.ProtoReflect.Descriptor instead.
func (*EditTweetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{9}
}

func (x *EditTweetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditTweetRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *EditTweetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EditTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditTweetResponse) Reset() {
	*x = EditTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTweetResponse) ProtoMessage() {}

func (x *EditTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTweetResponse.ProtoReflect.Descriptor instead.
func (*EditTweetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{10}
}

type DeletePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{12}
}

type LikePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{13}
}

func (x *LikePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LikePostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type LikePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{14}
}

type UnLikePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *UnLikePostRequest) Reset() {
	*x = UnLikePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnLikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnLikePostRequest) ProtoMessage() {}

func (x *UnLikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnLikePostRequest.ProtoReflect.Descriptor instead.
func (*UnLikePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{15}
}

func (x *UnLikePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnLikePostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type UnLikePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnLikePostResponse) Reset() {
	*x = UnLikePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnLikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnLikePostResponse) ProtoMessage() {}

func (x *UnLikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnLikePostResponse.ProtoReflect.Descriptor instead.
func (*UnLikePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{16}
}

type SavePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *SavePostRequest) Reset() {
	*x = SavePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePostRequest) ProtoMessage() {}

func (x *SavePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePostRequest.ProtoReflect.Descriptor instead.
func (*SavePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{17}
}

func (x *SavePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SavePostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type SavePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SavePostResponse) Reset() {
	*x = SavePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePostResponse) ProtoMessage() {}

func (x *SavePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePostResponse.ProtoReflect.Descriptor instead.
func (*SavePostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{18}
}

type UnSavePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid int64 `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *UnSavePostRequest) Reset() {
	*x = UnSavePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnSavePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSavePostRequest) ProtoMessage() {}

func (x *UnSavePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSavePostRequest.ProtoReflect.Descriptor instead.
func (*UnSavePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{19}
}

func (x *UnSavePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UnSavePostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type UnSavePostRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnSavePostRespone) Reset() {
	*x = UnSavePostRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnSavePostRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSavePostRespone) ProtoMessage() {}

func (x *UnSavePostRespone) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSavePostRespone.ProtoReflect.Descriptor instead.
func (*UnSavePostRespone) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{20}
}

type RplyCommentPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid   int64  `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
	Comment  string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Parentid int64  `protobuf:"varint,4,opt,name=parentid,proto3" json:"parentid,omitempty"`
}

func (x *RplyCommentPostRequest) Reset() {
	*x = RplyCommentPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RplyCommentPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RplyCommentPostRequest) ProtoMessage() {}

func (x *RplyCommentPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RplyCommentPostRequest.ProtoReflect.Descriptor instead.
func (*RplyCommentPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{21}
}

func (x *RplyCommentPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RplyCommentPostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *RplyCommentPostRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RplyCommentPostRequest) GetParentid() int64 {
	if x != nil {
		return x.Parentid
	}
	return 0
}

type RplyCommentPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RplyCommentPostResponse) Reset() {
	*x = RplyCommentPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RplyCommentPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RplyCommentPostResponse) ProtoMessage() {}

func (x *RplyCommentPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RplyCommentPostResponse.ProtoReflect.Descriptor instead.
func (*RplyCommentPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{22}
}

type CommentPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Postid  int64  `protobuf:"varint,2,opt,name=postid,proto3" json:"postid,omitempty"`
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CommentPostRequest) Reset() {
	*x = CommentPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPostRequest) ProtoMessage() {}

func (x *CommentPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPostRequest.ProtoReflect.Descriptor instead.
func (*CommentPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{23}
}

func (x *CommentPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentPostRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

func (x *CommentPostRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CommentPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommentPostResponse) Reset() {
	*x = CommentPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPostResponse) ProtoMessage() {}

func (x *CommentPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPostResponse.ProtoReflect.Descriptor instead.
func (*CommentPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{24}
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Postid int64 `protobuf:"varint,1,opt,name=postid,proto3" json:"postid,omitempty"`
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{25}
}

func (x *GetCommentsRequest) GetPostid() int64 {
	if x != nil {
		return x.Postid
	}
	return 0
}

type CommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Profile  string               `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Comment  string               `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Time     *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *CommentsResponse) Reset() {
	*x = CommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsResponse) ProtoMessage() {}

func (x *CommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsResponse.ProtoReflect.Descriptor instead.
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{26}
}

func (x *CommentsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentsResponse) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CommentsResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CommentsResponse) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comentdetails []*CommentsResponse `protobuf:"bytes,1,rep,name=comentdetails,proto3" json:"comentdetails,omitempty"`
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{27}
}

func (x *GetCommentsResponse) GetComentdetails() []*CommentsResponse {
	if x != nil {
		return x.Comentdetails
	}
	return nil
}

type EditCommentsRequet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Commentid int64  `protobuf:"varint,2,opt,name=commentid,proto3" json:"commentid,omitempty"`
	Comment   string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *EditCommentsRequet) Reset() {
	*x = EditCommentsRequet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCommentsRequet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentsRequet) ProtoMessage() {}

func (x *EditCommentsRequet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentsRequet.ProtoReflect.Descriptor instead.
func (*EditCommentsRequet) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{28}
}

func (x *EditCommentsRequet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditCommentsRequet) GetCommentid() int64 {
	if x != nil {
		return x.Commentid
	}
	return 0
}

func (x *EditCommentsRequet) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type EditCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditCommentsResponse) Reset() {
	*x = EditCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentsResponse) ProtoMessage() {}

func (x *EditCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentsResponse.ProtoReflect.Descriptor instead.
func (*EditCommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{29}
}

type DeleteCommentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Commentid int64 `protobuf:"varint,2,opt,name=commentid,proto3" json:"commentid,omitempty"`
}

func (x *DeleteCommentsRequest) Reset() {
	*x = DeleteCommentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentsRequest) ProtoMessage() {}

func (x *DeleteCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentsRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteCommentsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommentsRequest) GetCommentid() int64 {
	if x != nil {
		return x.Commentid
	}
	return 0
}

type DeleteCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentsResponse) Reset() {
	*x = DeleteCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentsResponse) ProtoMessage() {}

func (x *DeleteCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_tweet_tweet_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentsResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_tweet_tweet_proto_rawDescGZIP(), []int{31}
}

var File_pkg_pb_tweet_tweet_proto protoreflect.FileDescriptor

var file_pkg_pb_tweet_tweet_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2f, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x74,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x74, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x12, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x46, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x74,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x74, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x4f, 0x75, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x74,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x51, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x54, 0x77, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x70, 0x6f,
	0x73, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x73, 0x22, 0x5c, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x13, 0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x4c, 0x69, 0x6b,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x55, 0x6e, 0x4c, 0x69,
	0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x53,
	0x61, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x55, 0x6e,
	0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x6e, 0x53, 0x61, 0x76,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x76, 0x0a, 0x16,
	0x52, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x56, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x64, 0x22, 0xa2, 0x01, 0x0a,
	0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x54, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x65,
	0x6e, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x5c, 0x0a, 0x12, 0x45, 0x64, 0x69, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb5,
	0x08, 0x0a, 0x0c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3d, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x09, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x32, 0x12, 0x17, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x32, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x41, 0x64, 0x64,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12,
	0x19, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x72, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x72, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x45, 0x64, 0x69,
	0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x45,
	0x64, 0x69, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x08, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x6b,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0a, 0x55, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x2e,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x55, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e,
	0x55, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x16, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x55, 0x6e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x18, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x55, 0x6e, 0x53, 0x61, 0x76, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x55, 0x6e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x52, 0x70, 0x6c, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x52, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x2e, 0x52, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x19, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x45,
	0x64, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x45,
	0x64, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_tweet_tweet_proto_rawDescOnce sync.Once
	file_pkg_pb_tweet_tweet_proto_rawDescData = file_pkg_pb_tweet_tweet_proto_rawDesc
)

func file_pkg_pb_tweet_tweet_proto_rawDescGZIP() []byte {
	file_pkg_pb_tweet_tweet_proto_rawDescOnce.Do(func() {
		file_pkg_pb_tweet_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_tweet_tweet_proto_rawDescData)
	})
	return file_pkg_pb_tweet_tweet_proto_rawDescData
}

var file_pkg_pb_tweet_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_pkg_pb_tweet_tweet_proto_goTypes = []interface{}{
	(*AddTweetRequest)(nil),         // 0: tweet.AddTweetRequest
	(*AddTweetResponse)(nil),        // 1: tweet.AddTweetResponse
	(*AddTweet2Request)(nil),        // 2: tweet.AddTweet2Request
	(*AddTweet2Response)(nil),       // 3: tweet.AddTweet2Response
	(*GetOurTweetRequest)(nil),      // 4: tweet.GetOurTweetRequest
	(*TweetReponse)(nil),            // 5: tweet.TweetReponse
	(*GetOurTweetResponse)(nil),     // 6: tweet.GetOurTweetResponse
	(*GetOthersTweetRequest)(nil),   // 7: tweet.GetOthersTweetRequest
	(*GetOthersTweetResponse)(nil),  // 8: tweet.GetOthersTweetResponse
	(*EditTweetRequest)(nil),        // 9: tweet.EditTweetRequest
	(*EditTweetResponse)(nil),       // 10: tweet.EditTweetResponse
	(*DeletePostRequest)(nil),       // 11: tweet.DeletePostRequest
	(*DeletePostResponse)(nil),      // 12: tweet.DeletePostResponse
	(*LikePostRequest)(nil),         // 13: tweet.LikePostRequest
	(*LikePostResponse)(nil),        // 14: tweet.LikePostResponse
	(*UnLikePostRequest)(nil),       // 15: tweet.UnLikePostRequest
	(*UnLikePostResponse)(nil),      // 16: tweet.UnLikePostResponse
	(*SavePostRequest)(nil),         // 17: tweet.SavePostRequest
	(*SavePostResponse)(nil),        // 18: tweet.SavePostResponse
	(*UnSavePostRequest)(nil),       // 19: tweet.UnSavePostRequest
	(*UnSavePostRespone)(nil),       // 20: tweet.UnSavePostRespone
	(*RplyCommentPostRequest)(nil),  // 21: tweet.RplyCommentPostRequest
	(*RplyCommentPostResponse)(nil), // 22: tweet.RplyCommentPostResponse
	(*CommentPostRequest)(nil),      // 23: tweet.CommentPostRequest
	(*CommentPostResponse)(nil),     // 24: tweet.CommentPostResponse
	(*GetCommentsRequest)(nil),      // 25: tweet.GetCommentsRequest
	(*CommentsResponse)(nil),        // 26: tweet.CommentsResponse
	(*GetCommentsResponse)(nil),     // 27: tweet.GetCommentsResponse
	(*EditCommentsRequet)(nil),      // 28: tweet.EditCommentsRequet
	(*EditCommentsResponse)(nil),    // 29: tweet.EditCommentsResponse
	(*DeleteCommentsRequest)(nil),   // 30: tweet.DeleteCommentsRequest
	(*DeleteCommentsResponse)(nil),  // 31: tweet.DeleteCommentsResponse
	(*timestamp.Timestamp)(nil),     // 32: google.protobuf.Timestamp
}
var file_pkg_pb_tweet_tweet_proto_depIdxs = []int32{
	32, // 0: tweet.TweetReponse.time:type_name -> google.protobuf.Timestamp
	5,  // 1: tweet.GetOurTweetResponse.postdetails:type_name -> tweet.TweetReponse
	5,  // 2: tweet.GetOthersTweetResponse.postdetailss:type_name -> tweet.TweetReponse
	32, // 3: tweet.CommentsResponse.time:type_name -> google.protobuf.Timestamp
	26, // 4: tweet.GetCommentsResponse.comentdetails:type_name -> tweet.CommentsResponse
	0,  // 5: tweet.TweetService.AddTweet:input_type -> tweet.AddTweetRequest
	2,  // 6: tweet.TweetService.AddTweet2:input_type -> tweet.AddTweet2Request
	4,  // 7: tweet.TweetService.GetOurTweet:input_type -> tweet.GetOurTweetRequest
	7,  // 8: tweet.TweetService.GetOthersTweet:input_type -> tweet.GetOthersTweetRequest
	9,  // 9: tweet.TweetService.EditTweet:input_type -> tweet.EditTweetRequest
	11, // 10: tweet.TweetService.DeletePost:input_type -> tweet.DeletePostRequest
	13, // 11: tweet.TweetService.LikePost:input_type -> tweet.LikePostRequest
	15, // 12: tweet.TweetService.UnLikePost:input_type -> tweet.UnLikePostRequest
	17, // 13: tweet.TweetService.SavePost:input_type -> tweet.SavePostRequest
	19, // 14: tweet.TweetService.UnSavePost:input_type -> tweet.UnSavePostRequest
	21, // 15: tweet.TweetService.RplyCommentPost:input_type -> tweet.RplyCommentPostRequest
	23, // 16: tweet.TweetService.CommentPost:input_type -> tweet.CommentPostRequest
	25, // 17: tweet.TweetService.GetComments:input_type -> tweet.GetCommentsRequest
	28, // 18: tweet.TweetService.EditComments:input_type -> tweet.EditCommentsRequet
	30, // 19: tweet.TweetService.DeleteComments:input_type -> tweet.DeleteCommentsRequest
	1,  // 20: tweet.TweetService.AddTweet:output_type -> tweet.AddTweetResponse
	3,  // 21: tweet.TweetService.AddTweet2:output_type -> tweet.AddTweet2Response
	6,  // 22: tweet.TweetService.GetOurTweet:output_type -> tweet.GetOurTweetResponse
	8,  // 23: tweet.TweetService.GetOthersTweet:output_type -> tweet.GetOthersTweetResponse
	10, // 24: tweet.TweetService.EditTweet:output_type -> tweet.EditTweetResponse
	12, // 25: tweet.TweetService.DeletePost:output_type -> tweet.DeletePostResponse
	14, // 26: tweet.TweetService.LikePost:output_type -> tweet.LikePostResponse
	16, // 27: tweet.TweetService.UnLikePost:output_type -> tweet.UnLikePostResponse
	18, // 28: tweet.TweetService.SavePost:output_type -> tweet.SavePostResponse
	20, // 29: tweet.TweetService.UnSavePost:output_type -> tweet.UnSavePostRespone
	22, // 30: tweet.TweetService.RplyCommentPost:output_type -> tweet.RplyCommentPostResponse
	24, // 31: tweet.TweetService.CommentPost:output_type -> tweet.CommentPostResponse
	27, // 32: tweet.TweetService.GetComments:output_type -> tweet.GetCommentsResponse
	29, // 33: tweet.TweetService.EditComments:output_type -> tweet.EditCommentsResponse
	31, // 34: tweet.TweetService.DeleteComments:output_type -> tweet.DeleteCommentsResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_pb_tweet_tweet_proto_init() }
func file_pkg_pb_tweet_tweet_proto_init() {
	if File_pkg_pb_tweet_tweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_tweet_tweet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTweet2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTweet2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOurTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOurTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOthersTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOthersTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnLikePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnLikePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnSavePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnSavePostRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RplyCommentPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RplyCommentPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCommentsRequet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_tweet_tweet_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_tweet_tweet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_tweet_tweet_proto_goTypes,
		DependencyIndexes: file_pkg_pb_tweet_tweet_proto_depIdxs,
		MessageInfos:      file_pkg_pb_tweet_tweet_proto_msgTypes,
	}.Build()
	File_pkg_pb_tweet_tweet_proto = out.File
	file_pkg_pb_tweet_tweet_proto_rawDesc = nil
	file_pkg_pb_tweet_tweet_proto_goTypes = nil
	file_pkg_pb_tweet_tweet_proto_depIdxs = nil
}
