definitions:
  models.AdminLogin:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  models.UserProfile:
    properties:
      bio:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      phone:
        type: string
      profile:
        type: string
      username:
        type: string
    type: object
  models.UserSignup:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
info:
  contact:
    name: API Support
  description: Tweet Here is a social Media Platform
  title: Go + Gin SocailMedia TweetHere
  version: 1.0.0
paths:
  /admin/login:
    post:
      consumes:
      - application/json
      description: Login handler for Zsoxial admins
      parameters:
      - description: Admin login details
        in: body
        name: adminDetails
        required: true
        schema:
          $ref: '#/definitions/models.AdminLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Login
      tags:
      - Admin
  /user/login:
    post:
      consumes:
      - application/json
      description: Login handler for users
      parameters:
      - description: User login details
        in: body
        name: userDetails
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Login
      tags:
      - User
  /user/signup:
    post:
      consumes:
      - application/json
      description: Sign up handler for new users
      parameters:
      - description: User sign up details
        in: body
        name: userDetails
        required: true
        schema:
          $ref: '#/definitions/models.UserSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Sign Up
      tags:
      - User
  /users/profile:
    put:
      consumes:
      - application/json
      description: Update profile handler for users
      parameters:
      - description: User profile details
        in: body
        name: userDetails
        required: true
        schema:
          $ref: '#/definitions/models.UserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/response.Response'
      summary: User Update Profile
      tags:
      - User
securityDefinitions:
  BearerTokenAuth:
    in: headercd
    name: Authorization
    type: apiKey
swagger: "2.0"
