apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  namespace: tweethere
  labels:
    db: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      database: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        database: postgres
    spec:
      containers:
        - name: tweethere-postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              # value: "8086"
              valueFrom:
                secretKeyRef:
                  name: tweethere-k8s-secret
                  key: postgres-password  
          volumeMounts:
          - name: storagespace
            mountPath: /var/lib/postgresql/data
            subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: storagespace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi                                                                    

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tweethere
spec:
  type: ClusterIP
  selector:
    database: postgres
  ports:
    - port: 5432
      targetPort: 5432
